### ISSUE TITLE
Creates only table in postgres database

### ISSUE THREAD

**Issue by chichur** [RekGRpth/pg_task#11]
After install extension and reload cluster. table **task** created only in database postgres. How to use extensions in another databases?

postgresql version: 16
OS: Linux machine 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RekGRpth** [comment]
Read the [readme](https://github.com/RekGRpth/pg_task/blob/master/README.md) or [article](https://github.com/RekGRpth/RekGRpth/blob/main/Asynchronous%20Job%20Scheduler.md).

**Comment by chichur** [comment]
I added `pg_task.json = '[{"data":"database","user":"username"}]` to **postgresql.conf**
note: username must be superuser

**Comment by RekGRpth** [comment]
> username must be superuser

This is not necessary, the main thing is to have the necessary rights or, in general, you can first manually create the database and/or user.

**Comment by chichur** [comment]
When i create user without superuser privileges, got error.
```sql 
create role username with login;
create database database1 owner username encoding utf8 lc_collate 'ru_RU.utf8' lc_ctype 'ru_RU.utf8' template 'template0';
```
update config:
`pg_task.json = '{"data":"database1","user":"username"}]'`

```sql 
database1=> INSERT INTO task (input) VALUES ('SELECT now()');
ОШИБКА:  нет доступа к таблице pg_authid
КОНТЕКСТ:  SQL-оператор: "SELECT pg_catalog.pg_cancel_backend(pid) FROM "pg_catalog"."pg_locks" WHERE "locktype" OPERATOR(pg_catalog.=) 'userlock' AND "mode" OPERATOR(pg_catalog.=) 'AccessExclusiveLock' AND "granted" AND "objsubid" OPERATOR(pg_catalog.=) 3 AND "database" OPERATOR(pg_catalog.=) (SELECT "oid" FROM "pg_catalog"."pg_database" WHERE "datname" OPERATOR(pg_catalog.=) current_catalog) AND "classid" OPERATOR(pg_catalog.=) (SELECT "oid" FROM "pg_catalog"."pg_authid" WHERE "rolname" OPERATOR(pg_catalog.=) current_user) AND "objid" OPERATOR(pg_catalog.=) -237542957"
функция PL/pgSQL public.task_wake_up(), строка 1, оператор PERFOR
```

What rights should there be?

**Comment by RekGRpth** [comment]
> ```sql
> database1=> INSERT INTO task (input) VALUES ('SELECT now()');
> ОШИБКА:  нет доступа к таблице pg_authid
> КОНТЕКСТ:  SQL-оператор: "SELECT pg_catalog.pg_cancel_backend(pid) FROM "pg_catalog"."pg_locks" WHERE "locktype" OPERATOR(pg_catalog.=) 'userlock' AND "mode" OPERATOR(pg_catalog.=) 'AccessExclusiveLock' AND "granted" AND "objsubid" OPERATOR(pg_catalog.=) 3 AND "database" OPERATOR(pg_catalog.=) (SELECT "oid" FROM "pg_catalog"."pg_database" WHERE "datname" OPERATOR(pg_catalog.=) current_catalog) AND "classid" OPERATOR(pg_catalog.=) (SELECT "oid" FROM "pg_catalog"."pg_authid" WHERE "rolname" OPERATOR(pg_catalog.=) current_user) AND "objid" OPERATOR(pg_catalog.=) -237542957"
> функция PL/pgSQL public.task_wake_up(), строка 1, оператор PERFOR
> ```

fixed by https://github.com/RekGRpth/pg_task/commit/cc7c2471b67fdb23e24981a76a56eba849124640, thanx for report!

**Comment by RekGRpth** [comment]
> ```sql
> create role username with login;
> create database database1 owner username encoding utf8 lc_collate 'ru_RU.utf8' lc_ctype 'ru_RU.utf8' template 'template0';
> ```

In fact, it is not necessary to create a database and/or user in advance, pg_task will create them itself if necessary.
