### ISSUE TITLE
which Postgres version are supported?

### ISSUE THREAD

**Issue by lij55** [RekGRpth/pg_task#2]
I noticed `PG_VERSION_NUM >= 130000` and `PG_VERSION_NUM >= 140000` but what about others? like 9.x?
I tried to built with PG9.4 but missed a lot of headers files.

**Comment by RekGRpth** [comment]
I support only 13 and 14 versions now

**Comment by RekGRpth** [comment]
I have added support for 9, 10, 11 and 12 versions, but not tried to use they.

**Comment by RekGRpth** [comment]
I have added support for 9, 10, 11 and 12 versions, but not tried to use they.

**Comment by RekGRpth** [comment]
> but not tried to use they

I have written tests for all supported versions: 14, 13, 12, 11, 10 and 9
