### ISSUE TITLE
Version bump spam

### ISSUE THREAD

**Issue by Tostino** [RekGRpth/pg_task#3]
There seems to be a whole lot of releases getting put out for this repo on pgxn, I just wanted to check that it was intended?
Each time you bump the version of meta.json it is doing a full release, sending out a tweet, etc.

for example: 
![image](https://user-images.githubusercontent.com/8227578/141879689-4f76c987-f04b-49c4-9270-d2cf0b7c9bc9.png)

Also see here: https://pgxn.org/recent/

**Comment by RekGRpth** [comment]
If pgxn allows remove, I do it, but how?

**Comment by Tostino** [comment]
I don't speak for anyone but myself, but IMO i'd leave what's been done, but just change that going forward. Those releases are already out there as far as tweets, versions on pgxn, etc... just leave it and in the future do something different with your versioning IMO.

**Comment by RekGRpth** [comment]
I do not use any versioning, I has only one right version, and it is last version. But pgxn requires every different version to publish.

**Comment by Tostino** [comment]
If it were me, I would release minor versions a little less frequently. No one wants to keep up with software updating from under them 6 times in a work week.

**Comment by RekGRpth** [comment]
https://manager.pgxn.org/howto#thatssometa

> If you don’t want to read through the Semantic Versioning 2.0.0 spec, just use thee-part dotted integers (such as “1.2.0”) and don’t worry about it.

I do so ;)

**Comment by sjstoelting** [comment]
No, you don't do semantic versioning.
None of your so called versions can be reconstructed.
There is a reason for having tags in Git.

**Comment by RekGRpth** [comment]
> you don't do semantic versioning.

I write so and I

> just use thee-part dotted integers (such as “1.2.0”) and don’t worry about it.

**Comment by theory** [comment]
There is no need to publish every minor change, like for every commit. Please consider making thoughtful, complete releases with enumerable changes in a change log and meaningful version numbers.

**Comment by RekGRpth** [comment]
If it is possible to delete version, I will delete all versions and keep only latest.

**Comment by theory** [comment]
That's not the point. What I don't understand is why there are so many releases in such short periods of time, as if you were releasing on every commit.
