### ISSUE TITLE
SQL queries for PG_11

### ISSUE THREAD

**Issue by DiSalihov** [RekGRpth/pg_task#4]
Hello!
Perhaps this is already known, but some SQL queries are not executed in PostgreSQL 11.
Thanks

`WITH j AS ( SELECT COALESCE(j.user, current_setting('pg_task.default_user', false)) AS user, COALESCE(j.data, current_setting('pg_task.default_data', false)) AS data, schema, COALESCE(j.table, current_setting('pg_task.default_table', false)) AS table, COALESCE(reset, current_setting('pg_task.default_reset', false)::int4) AS reset, COALESCE(timeout, current_setting('pg_task.default_timeout', false)::int4) AS timeout, COALESCE(count, current_setting('pg_task.default_count', false)::int4) AS count, EXTRACT(epoch FROM COALESCE(live, current_setting('pg_task.default_live', false)::interval))::int8 AS live FROM json_populate_recordset(NULL::record, current_setting('pg_task.json', false)::json) AS j ("user" text, data text, schema text, "table" text, reset int4, timeout int4, count int4, live interval) ) SELECT DISTINCT COALESCE(u.usesysid, 0) AS user_oid, COALESCE(oid, 0) AS data_oid, COALESCE(pid, 0) AS pid, j.* FROM j LEFT JOIN pg_user AS u ON usename = j.user LEFT JOIN pg_database AS d ON datname = data AND NOT datistemplate AND datallowconn AND (usesysid IS NULL OR usesysid = datdba) LEFT JOIN pg_stat_activity AS a ON a.usename = j.user AND a.datname = data AND application_name = concat_ws(' ', 'pg_work', schema, j.table, reset::text, timeout::text) AND pid != pg_backend_pid();`
ERROR:  column "oid" does not exist
LINE 1: ...NCT COALESCE(u.usesysid, 0) AS user_oid, COALESCE(oid, 0) AS...
---------------------------------------------------------------------^
HINT:  There is a column named "oid" in table "d", but it cannot be referenced from this part of the query.
    
`CREATE TYPE state AS ENUM ('PLAN', 'TAKE', 'WORK', 'DONE', 'FAIL', 'STOP');`
`CREATE TABLE task ( id bigserial NOT NULL PRIMARY KEY, parent int8 DEFAULT current_setting('pg_task.id', true)::int8 REFERENCES task (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL, plan timestamptz NOT NULL DEFAULT current_timestamp, start timestamptz, stop timestamptz, live interval NOT NULL DEFAULT '0 sec', timeout interval NOT NULL DEFAULT '0 sec', repeat interval NOT NULL DEFAULT '0 sec', hash int4 NOT NULL GENERATED ALWAYS AS (hashtext("group"||COALESCE(remote, ''))) STORED, count int4 NOT NULL DEFAULT 0, max int4 NOT NULL DEFAULT ~(1<<31), pid int4, state state NOT NULL DEFAULT 'PLAN'::state, delete boolean NOT NULL DEFAULT false, drift boolean NOT NULL DEFAULT true, append boolean NOT NULL DEFAULT false, header boolean NOT NULL DEFAULT true, string boolean NOT NULL DEFAULT true, delimiter "char" NOT NULL DEFAULT '\t', escape "char", quote "char", error text, "group" text NOT NULL DEFAULT 'group', input text NOT NULL, "null" text NOT NULL DEFAULT '\\N', output text, remote text );`
ERROR:  syntax error at or near "("
LINE 1: ...T '0 sec', hash int4 NOT NULL GENERATED ALWAYS AS (hashtext(...
----------------------------------------------------------------------^

**Comment by RekGRpth** [comment]
> LINE 1: ...NCT COALESCE(u.usesysid, 0) AS user_oid, COALESCE(oid, 0) AS...

There is no such code in last version!

**Comment by RekGRpth** [comment]
> ERROR: syntax error at or near "("
> LINE 1: ...T '0 sec', hash int4 NOT NULL GENERATED ALWAYS AS (hashtext(...

fixed by https://github.com/RekGRpth/pg_task/commit/52b1331195edd71a61f4d914113fa42bfd0ede21 thank You!
