### ISSUE TITLE
Failure when "group" text is too long

### ISSUE THREAD

**Issue by RichMacDonald** [RekGRpth/pg_task#6]
My tasks loop repeatedly, so I use the "repeat" field. Because I want to clean up by deleting old records, I created a custom field, e.g., "user_key" for each type of task, so I could use `delete task where user_key = 'task_key1".

However, when subsequent records are inserted after the first execution, the custom fields are not populated. So I cannot use it to "group" my tasks.

So I tried to use the "group" field instead.

However, as soon as I used a value for "group" that was different from the string 'group', it failed. After some trial and error, I realized it was the length of the string that case causing the problem:

````sql
INSERT INTO tasks.task (input, repeat, drift, "group") VALUES (
	'SELECT NOW()', '1 sec', FALSE, 'this-group-name-works');
````

````sql	
INSERT INTO tasks.task (input, repeat, drift, "group") VALUES (
	'SELECT NOW();', '1 sec', FALSE, 'but a very long group name causes an error. Something about this long is too long.');

--Causes the tasks table record to hang with "state=PLAN"

--And the following in the postgres log file
--ERROR:  snprintf 103 >= 95
--LOG:  background worker "postgres pg_work tasks task 1000" (PID 35) exited with exit code 1
--WARNING:  unable to map dynamic shared memory segment
--WARNING:  row = 0, reset id =
````

Aside: Because the columns names are reserved words such as group, max, null, etc, they have to be surrounded with double-quotes. You may want to update the readme file to show this.

**Comment by RekGRpth** [comment]
> Because I want to clean up by deleting old records, I created a custom field, e.g., "user_key" for each type of task, so I could use `delete task where user_key = 'task_key1".

it is not necessary because if "delete" field is true and output is null and error is null then pg_task deletes record automatically

**Comment by RekGRpth** [comment]
> However, as soon as I used a value for "group" that was different from the string 'group', it failed. After some trial and error, I realized it was the length of the string that case causing the problem:
> 
> ```sql
> INSERT INTO tasks.task (input, repeat, drift, "group") VALUES (
> 	'SELECT NOW()', '1 sec', FALSE, 'this-group-name-works');
> ```
> 
> ```sql
> INSERT INTO tasks.task (input, repeat, drift, "group") VALUES (
> 	'SELECT NOW();', '1 sec', FALSE, 'but a very long group name causes an error. Something about this long is too long.');
> 
> --Causes the tasks table record to hang with "state=PLAN"
> 
> --And the following in the postgres log file
> --ERROR:  snprintf 103 >= 95
> --LOG:  background worker "postgres pg_work tasks task 1000" (PID 35) exited with exit code 1
> --WARNING:  unable to map dynamic shared memory segment
> --WARNING:  row = 0, reset id =
> ```

fixed, thanx for issue!

**Comment by RichMacDonald** [comment]
I am afraid I still see the error.

**Comment by RekGRpth** [comment]
> I still see the error

how You build?

**Comment by RichMacDonald** [comment]
```
FROM citusdata/citus:latest
#...including postgis, pgrouting, and mobilitydb
RUN apt-get install --yes build-essential make postgresql-server-dev-15 git wget libkrb5-dev systemtap-sdt-dev
RUN git clone https://github.com/RekGRpth/pg_task.git
WORKDIR pg_task
RUN make
RUN make install
```
Docker build with --no-cache.
Connecting to an existing database or creating a new database.

**Comment by RekGRpth** [comment]
I can not reproduce after fix

**Comment by RichMacDonald** [comment]
Today it works. Both with citusdata and with postgres/latest.

I wonder what could be causing the delay in getting updates. What else to do besides --no-cache, hmm.

Is there a version check for pg_task? A SQL function I can call to get the version number of the release? I don't know any other way to guarantee I am up to date.

Anyway, issue closed. Thank you.

**Comment by RekGRpth** [comment]
> Is there a version check for pg_task?

Not now

**Comment by RekGRpth** [comment]
> My tasks loop repeatedly, so I use the "repeat" field. Because I want to clean up by deleting old records, I created a custom field, e.g., "user_key" for each type of task, so I could use `delete task where user_key = 'task_key1".
> 
> However, when subsequent records are inserted after the first execution, the custom fields are not populated. So I cannot use it to "group" my tasks.

I add custom user field "data" for that, but You should drop table task first

**Comment by RekGRpth** [comment]
> the custom fields are not populated

I solve this problem too
