### ISSUE TITLE
pg_task error when make Postgresql 16 on Ubuntu 23

### ISSUE THREAD

**Issue by handyssutanto** [RekGRpth/pg_task#8]
sed -i 's/TRACE_POSTGRESQL_QUERY_/\/\/TRACE_POSTGRESQL_QUERY_/' postgres.c
sed -i 's/BeginCommand/BeginCommandMy/' postgres.c
sed -i 's/CreateDestReceiver/CreateDestReceiverMy/' postgres.c
sed -i 's/EndCommand/EndCommandMy/' postgres.c
sed -i 's/NullCommand/NullCommandMy/' postgres.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fno-omit-frame-pointer -fPIC -fvisibility=hidden -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/16/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o dest.o dest.c
In file included from dest.c:141:
./postgres.c:3049:1: warning: no previous prototype for ‘RecoveryConflictInterrupt’ [-Wmissing-prototypes]
 3049 | RecoveryConflictInterrupt(ProcSignalReason reason)

please help, thank you

**Comment by RekGRpth** [comment]
it is a race when using -j flag: postgres.c is not dowloaded yet, while dest.c is started compiling
try again and/or without it
